PRAGMA defer_foreign_keys=TRUE;
BEGIN TRANSACTION;
-- Keep isolate collection metadata aligned with prod-remote backup
INSERT OR REPLACE INTO "collections" ("id","name","tagline","description","badge","sort_order","is_active","created_at","updated_at","specs_json","documents_json","reviews_json","shipping_md","isolates_json","terpenes_json","images_json") VALUES('isolate-collection','Isolate','Single isolate product line','Dedicated isolate collection','Isolates',999,1,'2026-02-23 12:57:28','2026-03-09T19:02:26.962Z','[]','[]','[]','','[]','[]','[]');

-- Missing flavor profiles from prod-remote.sql
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('121037b2-c805-46d8-9a55-97ee7fbddb42','isolate-collection','beta-myrcene','Beta-Myrcene','Natural Botanical Isolate','Monoterpene','Beta-Myrcene is one of the most abundant terpenes found in botanical aromatic systems. It delivers a rich earthy backbone with soft fruity nuances, commonly used to build depth and body in flavor formulations.','Relaxation Grounding','[]','["Earthy","Herbal","Musky","Clove"]',2,1,'2026-03-09T18:55:10.748Z','2026-03-09T18:56:06.212Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('f1501166-aac2-408e-b810-1d8744a80562','isolate-collection','d-limonene','D-Limonene','Natural Botanical Isolate','Monoterpene','D-Limonene is a highly recognizable citrus terpene widely used in flavor and aromatic formulations. It delivers a bright, juicy citrus top note that enhances freshness and adds sparkling character to terpene blends and flavor systems.','Uplifting Energy Refreshing','[]','["Bright citrus","sweet orange","lemon peel","fresh zest notes"]',3,1,'2026-03-09T18:55:39.323Z','2026-03-09T18:59:29.288Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('47529ac9-e4d7-442e-b5a5-cb5ff1e0050a','isolate-collection','beta-caryophyllene','Beta-Caryophyllene','Natural Botanical Isolate','Sesquiterpene','Beta-Caryophyllene is a robust sesquiterpene known for its characteristic peppery spice and woody depth. It is commonly used in terpene and flavor formulations to add warmth, structure, and complexity to the base of aromatic profiles.','Grounded','[]','["Warm","Woody","Spicy","Black Pepper","Clove","Dry Herbal Notes"]',4,1,'2026-03-09T19:01:39.148Z','2026-03-09T19:02:09.143Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('03023a64-393c-464d-9001-d514f27f0e8c','isolate-collection','alpha-pinene','Alpha-Pinene','Natural Botanical Isolate','Monoterpene','Alpha-Pinene is known for its clean pine-forward aroma reminiscent of evergreen forests.  Adds freshness, lift, and natural green character to aromatic profiles.','Clarifying Energy','[]','["Fresh Pine","Woody Undertones"]',5,1,'2026-03-09T19:11:06.095Z','2026-03-09T19:11:15.478Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('454a91ae-ad2f-496a-b807-37327dfee3ba','isolate-collection','beta-pinene','Beta-Pinene','Natural Botanical Isolate','Monoterpene','Beta-Pinene is a naturally occurring monoterpene known for its sharp pine aroma and fresh green character. It is commonly used in terpene and flavor formulations to enhance brightness, add herbal freshness, and support natural forest-like aromatic complexity.','Uplifting Energy','[]','["Fresh","Woody","Pine","Crisp Green Herbal Notes","subtle spice and resin"]',6,1,'2026-03-09T19:13:21.794Z','2026-03-09T19:24:08.675Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('d846aa29-c2bd-4f31-a344-567e07890118','isolate-collection','terpinolene','Terpinolene','Natural Botanical Isolate','Monoterpene','Terpinolene is known for its layered aromatic profile combining sweet citrus, herbal freshness, and light pine. Commonly used in terpene and flavor formulations to add brightness, complexity, and vibrant top notes to aromatic blends.','Uplifting, Energy','[]','["Fresh","Sweet Herbal","Citrus Peel","Pine","Light Floral Spice"]',7,1,'2026-03-09T19:29:26.752Z','2026-03-09T19:29:26.752Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('d6521568-7126-46cc-b1da-87525822fdb7','isolate-collection','alpha-humulene','Alpha-Humulene','Natural Botanical Isolate','Sesquiterpene','Alpha-Humulene is recognized for its dry woody character and subtle herbal spice. Commonly found in hops and other botanicals, it is used in terpene and flavor formulations to provide earthy complexity and a refined base note.','Grounded Balanced','[]','["Woody","Earthy","Slightly Spicy","Subtle Herbal","Hop-like notes"]',8,1,'2026-03-09T19:32:38.202Z','2026-03-09T19:32:38.202Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('451598fc-814e-452a-b8d7-453d5185cd50','isolate-collection','camphene','Camphene','Natural Botanical Isolate','Monoterpene','Camphene is known for its sharp, camphor-like aroma and fresh woody character. Used to enhance freshness, add structure to top notes, and support bright aromatic complexity.','Crisp Cooling Refresing','[]','["Sharp","Woody","Herbal","Cool Camphoraceous","Subtle Pine"]',9,1,'2026-03-09T19:44:15.384Z','2026-03-09T19:44:15.384Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('0e81625f-35d4-475a-aeef-c3b2bf098382','isolate-collection','sabinene','Sabinene','Natural Botanical Isolate','Monoterpene','Sabinene is known for its fresh citrus-spice character and green herbal complexity. Used to introduce brightness, light spice, and aromatic lift to complex blends.','Energy','[]','["Fresh","Spicy","Woody","Citrus peel","Green Herbal Notes","Hint of Black Pepper"]',10,1,'2026-03-09T20:33:24.816Z','2026-03-09T20:33:24.816Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('dfb1a33e-eb6f-499c-addf-d5e030f79735','isolate-collection','fenchol','Fenchol','Natural Botanical Isolate','Monoterpene Alcohol','Fenchol is recognized for its fresh herbal aroma and mild camphor-like character. Used to enhance clean, cooling notes and support fresh botanical complexity.','Clean, Cooling, Clarifying','[]','["Fresh","Herbal","Slight Camphoraceous","Soft Pine","Subtle earthy undertones"]',11,1,'2026-03-09T20:36:19.820Z','2026-03-09T20:36:19.820Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('4e726121-2480-4671-96a1-a4dfe7833db5','isolate-collection','delta-3-carene','Delta-3-Carene','Natural Botanical Isolate','Monoterpene','Delta-3-Carene is known for its sweet woody aroma and crisp pine character. Used to enhance freshness, support citrus and pine top notes, and add natural depth to aromatic profiles.','Uplifting Energy','[]','["Sweet","Woody","Fresh","Pine","Subtle Citrus Peel"]',12,1,'2026-03-09T20:46:36.704Z','2026-03-09T20:48:48.027Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('f0f8e447-5c7d-4449-9cee-e7b4e81d4404','isolate-collection','isopulegol','Isopulegol','Natural Botanical Isolate','Monoterpene Alcohol','Isopulegol known for its soft minty freshness and subtle citrus character. It is commonly used in terpene and flavor formulations to introduce cooling notes, enhance freshness, and support bright aromatic top notes.','Cooling Refreshing Uplifting','[]','["Fresh Minty Herbal","Light Citrus Peel","Cooling Sweetness"]',13,1,'2026-03-09T21:00:29.758Z','2026-03-09T21:00:29.758Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('1c388182-9e40-48f6-a9ed-efc89f029291','isolate-collection','guaiol','Guaiol','Natural Botanical Isolate','Sesquiterpene Alcohol','Guaiol is known for its smooth woody aroma and delicate floral nuances. Used to provide depth, balance, and a soft woody foundation to complex aromatic profiles.','Grounding Calm','[]','["Woody","Earthy","Slightly Floral","Subtle Pine","Rose-like undertones"]',14,1,'2026-03-09T21:11:01.403Z','2026-03-09T21:11:01.403Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('dd3de807-db3f-46f6-a788-8a1fe314a5f9','isolate-collection','gamma-terpinene','Gamma-Terpinene','Natural Botanical Isolate','Monoterpene','Gamma-Terpinene is known for its fresh citrus-forward character and subtle herbal complexity. Used  to enhance brightness, support citrus profiles, and add lively top-note freshness to aromatic blends.','Uplifting, Energy','[]','["Bright Citrus","Sweet lemon-lime","Light herbal spice","Fresh green notes"]',15,1,'2026-03-09T21:15:54.644Z','2026-03-09T21:15:54.644Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('12507221-6be4-4a2b-9eb9-2f1a64bc6fab','isolate-collection','valencene','Valencene','Natural Botanical Isolate','Sesquiterpene','Valencene is a naturally occurring sesquiterpene known for its distinctive sweet orange aroma. Found in citrus peels, used to enhance authentic orange character, add citrus depth, and support vibrant aromatic profiles.','Cheerful Uplift','[]','["Sweet Citrus","Rich Orange Peel","Subtle Woody Undertones"]',16,1,'2026-03-09T21:19:43.534Z','2026-03-09T21:19:43.534Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('d9bc31db-1458-4f8a-945a-c3b952527c57','isolate-collection','alpha-bisabolol','Alpha-Bisabolol','Natural Botanical Isolate','Sesquiterpene Alcohol','Alpha-Bisabolol is recognized for its delicate floral aroma and smooth sweetness. Used in terpene and flavor formulations to add softness, floral balance, and refined depth to aromatic profiles.','Calming, Relaxed','[]','["Soft Floral","Sweet","Chamomile","Light Honey","Subtle Woody Notes"]',17,1,'2026-03-09T21:29:35.403Z','2026-03-09T21:29:35.403Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('c73cf849-39a2-4711-87a1-60d495b8246a','isolate-collection','beta-ocimene','Beta-Ocimene','Natural Botanical Isolate','Monoterpene','Beta-Ocimene is known for its sweet herbal character and fresh green citrus nuances.  Used in terpene and flavor formulations to enhance brightness, introduce light fruitiness, and add fresh complexity to aromatic blends.','Bright Uplift Energy','[]','["Sweet","Herbal","Slightly Citrusy","Fresh Green Notes","Tropical undertones"]',18,1,'2026-03-09T21:32:00.381Z','2026-03-09T21:32:00.381Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('8d826c7b-861c-4f24-ba42-c1f03f8d0372','test','blue-lobster','Blue Lobster','','','','','[]','[]',18,1,'2026-03-14T01:46:15.252Z','2026-03-14T01:46:15.252Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('50b9af54-5880-498d-82ce-d72c30a95137','emerald-cut','original-glue','Original Glue','','','','','[]','[]',5,1,'2026-03-14T01:49:46.300Z','2026-03-14T01:49:46.300Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('ba678900-c9cf-47d1-a17f-e7097396694c','emerald-cut','emerald-jack','Emerald Jack','','','','','[]','[]',6,1,'2026-03-14T01:49:56.781Z','2026-03-14T01:49:56.781Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('3b6a7201-fb1d-43bd-94a0-2ccfef4f35f9','emerald-cut','lemon-tree','Lemon Tree','','','','','[]','[]',7,1,'2026-03-14T01:50:04.382Z','2026-03-14T01:50:04.382Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('2fc90387-fb8f-4973-8c50-9ea5dff6e04f','emerald-cut','strawberry-haze','Strawberry Haze','','','','','[]','[]',8,1,'2026-03-14T01:50:15.280Z','2026-03-14T01:50:15.280Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('1ac607a2-ff06-4966-94a7-94153b5e994b','emerald-cut','presidential-og','Presidential OG','','','','','[]','[]',9,1,'2026-03-14T01:50:28.130Z','2026-03-14T01:50:28.130Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('1f597dc1-0bbd-4cbc-85b5-3fe1ccff4e3f','emerald-cut','grapefruit-chem','Grapefruit Chem','','','','','[]','[]',10,1,'2026-03-14T01:50:37.561Z','2026-03-14T01:50:37.561Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('463f16c0-3018-4567-a54e-bd3b0956c65c','emerald-cut','orange-monster','Orange Monster','','','','','[]','[]',11,1,'2026-03-14T01:50:48.808Z','2026-03-14T01:50:48.808Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('10dbca02-f048-41bf-843d-1c7c7734dc4b','emerald-cut','purple-fruit','Purple Fruit','','','','','[]','[]',12,1,'2026-03-14T01:50:57.009Z','2026-03-14T01:50:57.009Z');
INSERT OR REPLACE INTO "flavor_profiles" ("id","collection_id","slug","name","flavor_type","flavor_category","description","mood","dominant_terpenes","flavor_aroma","sort_order","is_active","created_at","updated_at") VALUES('1b2edb36-fca9-4472-b072-27835ae02327','emerald-cut','biscotti-sherb','Biscotti Sherb','','','','','[]','[]',13,1,'2026-03-14T01:51:08.195Z','2026-03-14T01:51:08.195Z');
COMMIT;