-- migrations/0012_flavor_profile_sku_mappings.sql
-- Primary -> secondary flavor/SKU mappings for the Build Your Flavor Library widget.
-- This keeps the product page from showing the entire collection catalog and instead
-- shows only the mapped companion options for the selected primary flavor.

CREATE TABLE IF NOT EXISTS flavor_profile_sku_mappings (
  id TEXT PRIMARY KEY,
  primary_profile_id TEXT NOT NULL,
  secondary_profile_id TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (primary_profile_id) REFERENCES flavor_profiles(id) ON DELETE CASCADE,
  FOREIGN KEY (secondary_profile_id) REFERENCES flavor_profiles(id) ON DELETE CASCADE,
  UNIQUE (primary_profile_id, secondary_profile_id)
);

CREATE INDEX IF NOT EXISTS idx_flavor_profile_sku_mappings_primary
  ON flavor_profile_sku_mappings(primary_profile_id, is_active, sort_order, created_at);

CREATE INDEX IF NOT EXISTS idx_flavor_profile_sku_mappings_secondary
  ON flavor_profile_sku_mappings(secondary_profile_id, is_active, sort_order, created_at);

WITH raw(primary_name, secondary_name, sort_order) AS (
  VALUES
    ('OG Kush', 'Skywalker OG', 0),
    ('OG Kush', 'Bubba Kush', 1),
    ('OG Kush', 'Green Apple', 2),
    ('OG Kush', 'Ruby Grapefruit', 3),
    ('Skywalker OG', 'OG Kush', 0),
    ('Skywalker OG', 'Bubba Kush', 1),
    ('Skywalker OG', 'Pineapple Sol', 2),
    ('Skywalker OG', 'Mango Nectar', 3),
    ('Acapulco Gold', 'Mango Nectar', 0),
    ('Acapulco Gold', 'Pineapple Sol', 1),
    ('Acapulco Gold', 'Tangerine', 2),
    ('Acapulco Gold', 'Passion Fruit', 3),
    ('King Louie XIII', 'OG Kush', 0),
    ('King Louie XIII', 'Bubba Kush', 1),
    ('King Louie XIII', 'Pistachio Baklava', 2),
    ('King Louie XIII', 'Black Sesame Honey', 3),
    ('Blue Dream', 'Blueberry Burst', 0),
    ('Blue Dream', 'Strawberry Luxe', 1),
    ('Blue Dream', 'Cereal Milk', 2),
    ('Blue Dream', 'Ube Vanilla Cream', 3),
    ('Chemdawg', 'Sour Diesel', 0),
    ('Chemdawg', 'Permanent Marker', 1),
    ('Chemdawg', 'Green Apple', 2),
    ('Chemdawg', 'Lime Note', 3),
    ('Sour Diesel', 'Chemdawg', 0),
    ('Sour Diesel', 'Lemon Zest', 1),
    ('Sour Diesel', 'Ruby Grapefruit', 2),
    ('Sour Diesel', 'Green Apple', 3),
    ('Trainwreck', 'Super Lemon Haze', 0),
    ('Trainwreck', 'Lemon Zest', 1),
    ('Trainwreck', 'Pineapple Sol', 2),
    ('Trainwreck', 'Mango Nectar', 3),
    ('Amnesia Haze', 'Super Lemon Haze', 0),
    ('Amnesia Haze', 'Calamansi', 1),
    ('Amnesia Haze', 'Tangerine', 2),
    ('Amnesia Haze', 'Passion Fruit', 3),
    ('Durban Poison', 'Jack Herer', 0),
    ('Durban Poison', 'Green Apple', 1),
    ('Durban Poison', 'Lime Note', 2),
    ('Durban Poison', 'Bergamont', 3),
    ('Super Lemon Haze', 'Lemon Zest', 0),
    ('Super Lemon Haze', 'Calamansi', 1),
    ('Super Lemon Haze', 'Lime Note', 2),
    ('Super Lemon Haze', 'Orange Sunshine', 3),
    ('Roadkill Skunk', 'Sour Diesel', 0),
    ('Roadkill Skunk', 'Chemdawg', 1),
    ('Roadkill Skunk', 'Smokey Cherry', 2),
    ('Roadkill Skunk', 'Dark Chocolate Sea Salt', 3),
    ('Permanent Marker', 'Chemdawg', 0),
    ('Permanent Marker', 'Green Apple', 1),
    ('Permanent Marker', 'White Gusher', 2),
    ('Permanent Marker', 'Strawberry Luxe', 3),
    ('Green Jelly Rancher', 'Strawberry Luxe', 0),
    ('Green Jelly Rancher', 'Kiwi Chill', 1),
    ('Green Jelly Rancher', 'Sour Patch Watermelon', 2),
    ('Green Jelly Rancher', 'White Gusher', 3),
    ('Hawiiana Snow Cone', 'Bomb Pop', 0),
    ('Hawiiana Snow Cone', 'Pineapple Sol', 1),
    ('Hawiiana Snow Cone', 'Strawberry Luxe', 2),
    ('Hawiiana Snow Cone', 'Mango Nectar', 3),
    ('Rainbow Belts', 'Sour Patch Watermelon', 0),
    ('Rainbow Belts', 'Green Jelly Rancher', 1),
    ('Rainbow Belts', 'Peach Rings', 2),
    ('Rainbow Belts', 'White Gusher', 3),
    ('Sour Patch Watermelon', 'Watermelon Slush', 0),
    ('Sour Patch Watermelon', 'Green Apple', 1),
    ('Sour Patch Watermelon', 'Kiwi Chill', 2),
    ('Sour Patch Watermelon', 'Rainbow Belts', 3),
    ('Cotton Candy', 'Hubba Bubba', 0),
    ('Cotton Candy', 'Strawberry Nesiquik', 1),
    ('Cotton Candy', 'Cereal Milk', 2),
    ('Cotton Candy', 'Ube Vanilla Cream', 3),
    ('Hubba Bubba', 'Cotton Candy', 0),
    ('Hubba Bubba', 'Strawberry Nesiquik', 1),
    ('Hubba Bubba', 'White Gusher', 2),
    ('Hubba Bubba', 'Banana Shake', 3),
    ('White Gusher', 'Green Jelly Rancher', 0),
    ('White Gusher', 'Strawberry Luxe', 1),
    ('White Gusher', 'Kiwi Chill', 2),
    ('White Gusher', 'Pineapple Sol', 3),
    ('Peach Rings', 'Peach Nectar', 0),
    ('Peach Rings', 'Orange Sunshine', 1),
    ('Peach Rings', 'Strawberry Luxe', 2),
    ('Peach Rings', 'Mango Nectar', 3),
    ('Bomb Pop', 'Hawiiana Snow Cone', 0),
    ('Bomb Pop', 'Cola', 1),
    ('Bomb Pop', 'Cherry Amarena', 2),
    ('Bomb Pop', 'Blueberry Burst', 3),
    ('Yogurt Tart', 'Strawberry Luxe', 0),
    ('Yogurt Tart', 'Cereal Milk', 1),
    ('Yogurt Tart', 'Lemon Zest', 2),
    ('Yogurt Tart', 'Passion Fruit', 3),
    ('Tres Leches', 'Cereal Milk', 0),
    ('Tres Leches', 'Ube Vanilla Cream', 1),
    ('Tres Leches', 'Banana Shake', 2),
    ('Tres Leches', 'Pistachio Baklava', 3),
    ('Strawberries & Cream', 'Strawberry Luxe', 0),
    ('Strawberries & Cream', 'Cereal Milk', 1),
    ('Strawberries & Cream', 'Yogurt Tart', 2),
    ('Strawberries & Cream', 'Banana Shake', 3),
    ('Cereal Milk', 'Strawberry Nesiquik', 0),
    ('Cereal Milk', 'Cotton Candy', 1),
    ('Cereal Milk', 'Banana Shake', 2),
    ('Cereal Milk', 'Blueberry Burst', 3),
    ('Ube Vanilla Cream', 'Matcha Cream', 0),
    ('Ube Vanilla Cream', 'Tres Leches', 1),
    ('Ube Vanilla Cream', 'Cereal Milk', 2),
    ('Ube Vanilla Cream', 'Banana Shake', 3),
    ('Matcha Cream', 'Ube Vanilla Cream', 0),
    ('Matcha Cream', 'Black Sesame Honey', 1),
    ('Matcha Cream', 'Honeydew Slice', 2),
    ('Matcha Cream', 'Charr''d Coconut', 3),
    ('Black Sesame Honey', 'Matcha Cream', 0),
    ('Black Sesame Honey', 'Pistachio Baklava', 1),
    ('Black Sesame Honey', 'Dark Chocolate Sea Salt', 2),
    ('Black Sesame Honey', 'Tres Leches', 3),
    ('Dark Chocolate Sea Salt', 'Black Sesame Honey', 0),
    ('Dark Chocolate Sea Salt', 'Smokey Cherry', 1),
    ('Dark Chocolate Sea Salt', 'Pistachio Baklava', 2),
    ('Dark Chocolate Sea Salt', 'Banana Shake', 3),
    ('Mojito', 'Lime Note', 0),
    ('Mojito', 'Lemon Zest', 1),
    ('Mojito', 'Cucumber Mint', 2),
    ('Mojito', 'Calamansi', 3),
    ('Cucumber Mint', 'Mojito', 0),
    ('Cucumber Mint', 'Lime Note', 1),
    ('Cucumber Mint', 'Honeydew Slice', 2),
    ('Cucumber Mint', 'Green Apple', 3),
    ('Cola', 'Cherry Amarena', 0),
    ('Cola', 'Bomb Pop', 1),
    ('Cola', 'Dark Chocolate Sea Salt', 2),
    ('Cola', 'Ube Vanilla Cream', 3),
    ('Baha Blast', 'Lime Note', 0),
    ('Baha Blast', 'Pineapple Sol', 1),
    ('Baha Blast', 'Mango Nectar', 2),
    ('Baha Blast', 'Kiwi Chill', 3),
    ('Tajin', 'Lime Note', 0),
    ('Tajin', 'Orange Sunshine', 1),
    ('Tajin', 'Ruby Grapefruit', 2),
    ('Tajin', 'Calamansi', 3),
    ('Banana Shake', 'Strawberry Luxe', 0),
    ('Banana Shake', 'Mango Nectar', 1),
    ('Banana Shake', 'Cereal Milk', 2),
    ('Banana Shake', 'Pineapple Sol', 3),
    ('Blueberry Burst', 'Blueberry', 0),
    ('Blueberry Burst', 'Blackberry Noir', 1),
    ('Blueberry Burst', 'Strawberry Luxe', 2),
    ('Blueberry Burst', 'Cherry Amarena', 3),
    ('Strawberry Luxe', 'Strawberry Nesiquik', 0),
    ('Strawberry Luxe', 'Strawberries & Cream', 1),
    ('Strawberry Luxe', 'Banana Shake', 2),
    ('Strawberry Luxe', 'White Gusher', 3),
    ('Blackberry Noir', 'Blueberry Burst', 0),
    ('Blackberry Noir', 'Cherry Amarena', 1),
    ('Blackberry Noir', 'Vineyard Grape', 2),
    ('Blackberry Noir', 'Dark Chocolate Sea Salt', 3),
    ('Kiwi Chill', 'Green Apple', 0),
    ('Kiwi Chill', 'White Lychee', 1),
    ('Kiwi Chill', 'Pineapple Sol', 2),
    ('Kiwi Chill', 'Lime Note', 3),
    ('Pineapple Sol', 'Mango Nectar', 0),
    ('Pineapple Sol', 'Baha Blast', 1),
    ('Pineapple Sol', 'Kiwi Chill', 2),
    ('Pineapple Sol', 'Passion Fruit', 3),
    ('Mango Nectar', 'Pineapple Sol', 0),
    ('Mango Nectar', 'Passion Fruit', 1),
    ('Mango Nectar', 'Banana Shake', 2),
    ('Mango Nectar', 'Orange Sunshine', 3),
    ('Watermelon Slush', 'Sour Patch Watermelon', 0),
    ('Watermelon Slush', 'Kiwi Chill', 1),
    ('Watermelon Slush', 'Green Apple', 2),
    ('Watermelon Slush', 'Strawberry Luxe', 3),
    ('Peach Nectar', 'Peach Rings', 0),
    ('Peach Nectar', 'Mango Nectar', 1),
    ('Peach Nectar', 'Orange Sunshine', 2),
    ('Peach Nectar', 'Passion Fruit', 3),
    ('Orange Sunshine', 'Tangerine', 0),
    ('Orange Sunshine', 'Lemon Zest', 1),
    ('Orange Sunshine', 'Calamansi', 2),
    ('Orange Sunshine', 'Ruby Grapefruit', 3),
    ('Lemon Zest', 'Super Lemon Haze', 0),
    ('Lemon Zest', 'Lime Note', 1),
    ('Lemon Zest', 'Calamansi', 2),
    ('Lemon Zest', 'Bergamont', 3),
    ('Lime Note', 'Mojito', 0),
    ('Lime Note', 'Baha Blast', 1),
    ('Lime Note', 'Tajin', 2),
    ('Lime Note', 'Calamansi', 3),
    ('Green Apple', 'Green Jelly Rancher', 0),
    ('Green Apple', 'Kiwi Chill', 1),
    ('Green Apple', 'Sour Patch Watermelon', 2),
    ('Green Apple', 'White Gusher', 3),
    ('Ruby Grapefruit', 'Calamansi', 0),
    ('Ruby Grapefruit', 'Bergamont', 1),
    ('Ruby Grapefruit', 'Orange Sunshine', 2),
    ('Ruby Grapefruit', 'Lemon Zest', 3),
    ('Bergamont', 'Lemon Zest', 0),
    ('Bergamont', 'Tangerine', 1),
    ('Bergamont', 'Ruby Grapefruit', 2),
    ('Bergamont', 'Calamansi', 3),
    ('Tangerine', 'Orange Sunshine', 0),
    ('Tangerine', 'Calamansi', 1),
    ('Tangerine', 'Mango Nectar', 2),
    ('Tangerine', 'Lemon Zest', 3),
    ('Calamansi', 'Lime Note', 0),
    ('Calamansi', 'Tangerine', 1),
    ('Calamansi', 'Lemon Zest', 2),
    ('Calamansi', 'Orange Sunshine', 3),
    ('Honeydew Slice', 'Melonade', 0),
    ('Honeydew Slice', 'Cucumber Mint', 1),
    ('Honeydew Slice', 'Kiwi Chill', 2),
    ('Honeydew Slice', 'Watermelon Slush', 3),
    ('White Lychee', 'Kiwi Chill', 0),
    ('White Lychee', 'Passion Fruit', 1),
    ('White Lychee', 'Pineapple Sol', 2),
    ('White Lychee', 'Mango Nectar', 3),
    ('Passion Fruit', 'Mango Nectar', 0),
    ('Passion Fruit', 'Pineapple Sol', 1),
    ('Passion Fruit', 'White Lychee', 2),
    ('Passion Fruit', 'Orange Sunshine', 3),
    ('Jackfruit Nectar', 'Mango Nectar', 0),
    ('Jackfruit Nectar', 'Passion Fruit', 1),
    ('Jackfruit Nectar', 'Pineapple Sol', 2),
    ('Jackfruit Nectar', 'Banana Shake', 3),
    ('Melonade', 'Honeydew Slice', 0),
    ('Melonade', 'Watermelon Slush', 1),
    ('Melonade', 'Kiwi Chill', 2),
    ('Melonade', 'Lemon Zest', 3),
    ('Cherry Amarena', 'Smokey Cherry', 0),
    ('Cherry Amarena', 'Strawberry Luxe', 1),
    ('Cherry Amarena', 'Cola', 2),
    ('Cherry Amarena', 'Dark Chocolate Sea Salt', 3),
    ('Smokey Cherry', 'Cherry Amarena', 0),
    ('Smokey Cherry', 'Dark Chocolate Sea Salt', 1),
    ('Smokey Cherry', 'Blackberry Noir', 2),
    ('Smokey Cherry', 'Cola', 3),
    ('Rosemary Olive', 'Lemon Zest', 0),
    ('Rosemary Olive', 'Bergamont', 1),
    ('Rosemary Olive', 'Tajin', 2),
    ('Rosemary Olive', 'Orange Sunshine', 3),
    ('Pistachio Baklava', 'Black Sesame Honey', 0),
    ('Pistachio Baklava', 'Tres Leches', 1),
    ('Pistachio Baklava', 'Dark Chocolate Sea Salt', 2),
    ('Pistachio Baklava', 'Ube Vanilla Cream', 3)
),
normalized AS (
  SELECT
    TRIM(primary_name) AS primary_name,
    TRIM(secondary_name) AS secondary_name,
    sort_order
  FROM raw
)
INSERT OR IGNORE INTO flavor_profile_sku_mappings (
  id,
  primary_profile_id,
  secondary_profile_id,
  sort_order,
  is_active,
  created_at,
  updated_at
)
SELECT
  lower(hex(randomblob(16))) AS id,
  primary_fp.id AS primary_profile_id,
  secondary_fp.id AS secondary_profile_id,
  normalized.sort_order,
  1 AS is_active,
  datetime('now') AS created_at,
  datetime('now') AS updated_at
FROM normalized
JOIN flavor_profiles AS primary_fp
  ON primary_fp.name = normalized.primary_name
JOIN flavor_profiles AS secondary_fp
  ON secondary_fp.name = normalized.secondary_name
WHERE primary_fp.id <> secondary_fp.id;
