// Content sourced from your provided doc (collections + CTAs).
export const terpeneCollections = [
  {
    id: "fruity-fusion-forward",
    badge: "🌿 Botanical Profiles",
    name: "Amplify Collection",
    tagline: "Bold Fruit Formulations",
    description:
      "A bright, expressive lineup of botanical blends designed to deliver bold fruit character and aromatic complexity. Ideal for brands seeking vibrant, crowd-pleasing flavor profiles with consistent performance.",
    profiles: [
      "Blazin Banana",
      "Blueberry Wave",
      "Bursting Blackberry",
      "Candy Cherry",
      "Creamy Cake",
      "Goodness Grape-ness",
      "Mad Mango",
      "Peach Glow",
      "Yogurt Tart",
      "Rainbow Belts",
      "Sour Rancher Guava",
      "Strawberry",
      "Sunshine Orange",
      "Sweet Cream",
      "Tropical Pineapple",
      "Very Raspberry",
      "Watermelon",
    ],
  },
  {
    id: "inspired-profile-collection",
    badge: "🌱 Botanical Profiles",
    name: "Benchmark Collection",
    tagline: "Classic Terpene Formulations",
    description:
      "Our profile-inspired terpene blends are carefully composed to reflect well-known aroma and flavor benchmarks. Using botanical terpene isolates, each blend recreates the sensory characteristics associated with classic profiles—focusing on balance, depth, and consistency—while remaining entirely botanical in origin.",
    profiles: [
      "Animal Mints",
      "Apple Fritter",
      "Banana Kush",
      "Berry Gelato",
      "Berry White",
      "Biscotti",
      "Blueberry Kush",
      "Bubba Kush",
      "Bubblegum OG",
      "Chemdawg",
      "Do-Si-Dos",
      "Durban Poison",
      "Fire OG",
      "Girl Scout Cookies",
      "Gorilla Glue #4",
      "Grape Ape",
      "Hindu Kush",
      "Jack Herer",
      "Jet Fuel OG",
      "Kush Mints",
      "Lemon OG",
      "Limoncello",
      "Mai Tai",
      "Maui Wowie",
      "Northern Lights",
      "Permanent Marker (NEW)",
      "Purple Punch",
      "Rainbow Sherbet #11",
      "Slurricane",
      "Sour Diesel",
      "Sour OG",
      "Sour Tangie",
      "Strawnana",
      "Sundae Driver",
      "Sunset Sherbert",
      "Super Lemon Haze",
      "Super Silver Haze",
      "Tangie",
      "Tea Time (NEW)",
      "Trainwreck",
      "Wedding Cake",
      "White Fire OG",
      "White Runtz",
      "White Widow",
      "Zkittlez",
    ],
  },
  {
    id: "signature-blends",
    badge: "🌿 Botanical Profiles",
    name: "Signature Blends Matrix",
    tagline: "I cant leave this empty • must fill",
    description:
      "This category cleanly captures everything that is neither purely fruity nor clearly inspired, without overlap or confusion. It also scales very well as your catalog grows.",
    profiles: [
      "Birthday Cake",
      "Blackberry Kush",
      "Cadillac Rainbow",
      "Candy Rain",
      "Cereal Milk",
      "Cherry Pie",
      "Donut Shop",
      "Forbidden Fruit",
      "Fruity Pebbles",
      "Gelato #41",
      "Hawaiian Snow Cone",
      "Jelly Rancher",
      "Lemon Cream Diesel",
      "Lemonade",
      "Mango Kush",
      "Melonade",
      "Milkyway",
      "Mimosa",
      "Pancakes",
      "Papaya Punch",
      "Peach Crescendo",
      "Pineapple Express",
      "Pink Aura",
      "Strawberry Cough",
      "Tropical Burst (NEW)",
      "Tropicana Cookies",
      "Watermelon Zkittlez",
    ],
  },
  {
    id: "emerald-line",
    badge: "💎 Emerald Line — Capturing Authenticity",
    name: "Emerald I Cut",
    tagline: "Depth • balance • authenticity",
    description:
      "Our most refined terpene expressions. The Emerald Line focuses on depth, balance, and authenticity—crafted to deliver nuanced aroma and flavor true to original profile intent.",
    profiles: [
      "Emerald OG",
      "Emerald Citrus Reserve",
      "Emerald Berry Noir",
      "Emerald Pine Essence",
      "Emerald Floral Haze",
      "Emerald Cream Reserve",
      "Emerald Grape Essence",
      "Emerald Sweet Gas",
      "Emerald Earth & Spice",
      "Emerald Classic Reserve",
    ],
  },
];

export const heroCopy = {
  eyebrow: "Get 20% Off Your First Order!",
  blurb:
    "Our terpene offerings are formulated using botanical terpene isolates and structured into three clearly defined collections. Each line is designed to deliver consistent aroma and flavor performance—ranging from fruit-forward blends to profile-inspired compositions and high-fidelity expressions developed to capture authentic sensory characteristics.",
  secondaryBlurb: "New customers receive 20% off their first order.",
  ctas: ["Contact Us Today", "Start Your Order", "Request Samples"],
};
